<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USE2DEVP5773" failures="0" tests="1" name="ReadCellExample" time="74.744" errors="1" timestamp="2022-08-19T17:52:59 IST" skipped="0">
  <testcase classname="ReadCellExample" name="mainfunction" time="74.744">
    <error message="C:\Users\X023840\eclipse-workspace\LYNX_Automation\src\test\resources\TestImages\logon.PNG: (66x23) seen at (690, 425) with 0.95 in R[0,0 1366x768]@S(0)" type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: C:\Users\X023840\eclipse-workspace\LYNX_Automation\src\test\resources\TestImages\logon.PNG: (66x23) seen at (690, 425) with 0.95 in R[0,0 1366x768]@S(0)
  Line 2291, in file Region.java

at org.sikuli.script.Region.find(Region.java:2291)
at TEST.Login(TEST.java:52)
at ReadCellExample.mainfunction(ReadCellExample.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- mainfunction -->
  <system-out/>
</testsuite> <!-- ReadCellExample -->
